[workspace]
members = [
    "omokoda-core",
    "omokoda-hive",
    "omokoda-hermetic",
    "omokoda-mesh",
    "omokoda-cli",
    "omokoda-acp",
    "zangbeto-stub",
    "nautilus_integration",
    "nist_entropy",
    "oso-parser",
    "oso-compiler",
    "oso-sdk",
    "oso-wasm",
    "oso-linter",
    "oso-simulator",
    "oso-move",
    "oso-security",
    "oso-deployer",
]
resolver = "2"

[profile.dev]
debug = 0
strip = "debuginfo"
split-debuginfo = "off"
incremental = false
