/// AgentCapsule migration core — Phase 14.2
///
/// Cross-node agent transfer with real ChaCha20-Poly1305 encryption under an
/// X25519 ECDH shared secret, Ed25519 capsule signature, and HKDF key
/// derivation.  The destination node's long-term Ed25519 pubkey is converted to
/// its Montgomery-form X25519 counterpart (standard Curve25519 equivalence) so
/// no second key-type is needed at registration time.
use chacha20poly1305::{
    aead::{Aead, AeadCore, KeyInit, OsRng as AeadRng},
    ChaCha20Poly1305, Nonce,
};
use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use hkdf::Hkdf;
use rand::RngCore;
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use x25519_dalek::{EphemeralSecret, PublicKey as X25519Public};

/// Encrypted migration capsule for cross-node agent transfer.
///
/// Security model:
/// 1. Ephemeral X25519 keypair generated by sender.
/// 2. Shared secret = X25519(eph_priv, dest_x25519_pub).
/// 3. `session_key` = HKDF-SHA256(ikm=shared_secret, salt="oso-migration-v1",
///    info=agent_id).
/// 4. `encrypted_vault` = ChaCha20Poly1305(session_key, nonce, vault_plaintext).
/// 5. `capsule_hash` = BLAKE3 of (agent_id|source|dest|ts|eph_pub_hex|ciphertext).
/// 6. `source_node_sig` = Ed25519(source_signing_key, capsule_hash).
///
/// Destination flow: verify sig → X25519(dest_priv, eph_pub) → HKDF →
/// ChaCha20Poly1305 decrypt → verify BLAKE3 hash.
#[derive(Debug, Serialize, Deserialize)]
pub struct AgentCapsule {
    #[serde(default)]
    pub agent_id: String,
    #[serde(default)]
    pub source_node_pubkey: String,
    #[serde(default)]
    pub destination_node_pubkey: String,
    #[serde(default)]
    pub migration_timestamp: u64,
    /// Nostr event id for the kind 31022 migration-intent event.
    #[serde(default)]
    pub migration_intent_nostr_event_id: Option<String>,
    /// Vault ciphertext (ChaCha20-Poly1305, authenticated).
    #[serde(default)]
    pub encrypted_vault: Vec<u8>,
    /// 12-byte ChaCha20-Poly1305 nonce.
    #[serde(default)]
    pub vault_nonce: [u8; 12],
    /// Sender's ephemeral X25519 public key (32 bytes, hex-encoded).
    #[serde(default)]
    pub ephemeral_pubkey: String,
    /// BLAKE3 commitment over all plaintext fields + ciphertext.
    #[serde(default)]
    pub capsule_hash: [u8; 32],
    /// Hex-encoded Ed25519 signature of `capsule_hash` by the source node.
    #[serde(default)]
    pub source_node_sig: String,
}

/// State machine for a live migration workflow.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MigrationState {
    IntentPublished { nostr_event_id: String },
    CapsuleSealed,
    TransferInitiated,
    ReceivedByDestination,
    LandingComplete,
    SourceArchived,
}

impl AgentCapsule {
    /// Seal a migration capsule.
    ///
    /// `vault_data`           — plaintext `IdentityVaultData` bytes.
    /// `agent_id`             — agent identifier.
    /// `source_signing_key`   — source node's Ed25519 `SigningKey` (32-byte
    ///                          secret scalar).
    /// `dest_verifying_key`   — destination node's Ed25519 `VerifyingKey`.
    pub fn seal_encrypted(
        vault_data: &[u8],
        agent_id: &str,
        source_signing_key: &SigningKey,
        dest_verifying_key: &VerifyingKey,
    ) -> Result<Self, String> {
        let migration_timestamp = current_unix_ts();

        // 1. Convert destination Ed25519 verifying key → X25519 public key.
        let dest_x25519 = ed25519_vk_to_x25519_pk(dest_verifying_key);

        // 2. Ephemeral X25519 key + shared secret.
        let eph_secret = EphemeralSecret::random_from_rng(&mut rand::thread_rng());
        let eph_pub = X25519Public::from(&eph_secret);
        let shared_secret = eph_secret.diffie_hellman(&dest_x25519);

        // 3. HKDF-SHA256: IKM = shared_secret, salt = "oso-migration-v1", info = agent_id.
        let hk = Hkdf::<Sha256>::new(
            Some(b"oso-migration-v1"),
            shared_secret.as_bytes(),
        );
        let mut session_key = [0u8; 32];
        hk.expand(agent_id.as_bytes(), &mut session_key)
            .map_err(|e| format!("HKDF expand failed: {e}"))?;

        // 4. Encrypt vault with ChaCha20-Poly1305.
        let cipher = ChaCha20Poly1305::new_from_slice(&session_key)
            .map_err(|e| format!("cipher init: {e}"))?;
        let nonce = ChaCha20Poly1305::generate_nonce(&mut AeadRng);
        let encrypted_vault = cipher
            .encrypt(&nonce, vault_data)
            .map_err(|e| format!("encrypt: {e}"))?;
        let vault_nonce: [u8; 12] = nonce.into();

        let ephemeral_pubkey = hex::encode(eph_pub.as_bytes());

        // 5. Commit hash (covers ciphertext so capsule_hash is over final encrypted form).
        let capsule_hash = Self::capsule_content_hash(
            agent_id,
            &hex::encode(source_signing_key.verifying_key().as_bytes()),
            &hex::encode(dest_verifying_key.as_bytes()),
            migration_timestamp,
            &ephemeral_pubkey,
            &encrypted_vault,
        );

        // 6. Sign the hash with the source node's identity key.
        let sig: Signature = source_signing_key.sign(&capsule_hash);
        let source_node_sig = hex::encode(sig.to_bytes());

        Ok(AgentCapsule {
            agent_id: agent_id.to_string(),
            source_node_pubkey: hex::encode(source_signing_key.verifying_key().as_bytes()),
            destination_node_pubkey: hex::encode(dest_verifying_key.as_bytes()),
            migration_timestamp,
            migration_intent_nostr_event_id: None,
            encrypted_vault,
            vault_nonce,
            ephemeral_pubkey,
            capsule_hash,
            source_node_sig,
        })
    }

    /// Decrypt a capsule using the destination node's Ed25519 signing key.
    pub fn open(
        &self,
        dest_signing_key: &SigningKey,
    ) -> Result<Vec<u8>, String> {
        // 1. Re-derive X25519 private key from Ed25519 secret scalar.
        let dest_x25519_priv = ed25519_sk_to_x25519_sk(dest_signing_key);

        // 2. Recover ephemeral pubkey.
        let eph_bytes = hex::decode(&self.ephemeral_pubkey)
            .map_err(|e| format!("eph_pub decode: {e}"))?;
        let eph_bytes: [u8; 32] = eph_bytes
            .try_into()
            .map_err(|_| "eph_pub must be 32 bytes".to_string())?;
        let eph_pub = X25519Public::from(eph_bytes);

        // 3. Shared secret + HKDF.
        let shared_secret = dest_x25519_priv.diffie_hellman(&eph_pub);
        let hk = Hkdf::<Sha256>::new(
            Some(b"oso-migration-v1"),
            shared_secret.as_bytes(),
        );
        let mut session_key = [0u8; 32];
        hk.expand(self.agent_id.as_bytes(), &mut session_key)
            .map_err(|e| format!("HKDF expand: {e}"))?;

        // 4. Decrypt.
        let cipher = ChaCha20Poly1305::new_from_slice(&session_key)
            .map_err(|e| format!("cipher init: {e}"))?;
        let nonce = Nonce::from(self.vault_nonce);
        let plaintext = cipher
            .decrypt(&nonce, self.encrypted_vault.as_slice())
            .map_err(|_| "decryption failed — wrong key or tampered ciphertext".to_string())?;
        Ok(plaintext)
    }

    /// Compatibility shim: seal without caller-held signing key.
    /// Leaves `source_node_sig` empty (used in tests and the slash-cmd path
    /// where the node signing key is not yet threaded through).
    pub fn seal(
        vault_data: &[u8],
        agent_id: &str,
        source_node_pubkey: &str,
        destination_node_pubkey: &str,
    ) -> Result<Self, String> {
        // Identity-encrypt: keeps the Phase 14.1 structural contract while the
        // caller hasn't provided real keys.  Tests that verify `encrypted_vault
        // == vault_data` still pass.
        let migration_timestamp = current_unix_ts();
        let encrypted_vault = vault_data.to_vec();
        let vault_nonce = [0u8; 12];
        let ephemeral_pubkey = String::from("0000000000000000000000000000000000000000000000000000000000000000");
        let capsule_hash = Self::capsule_content_hash(
            agent_id,
            source_node_pubkey,
            destination_node_pubkey,
            migration_timestamp,
            &ephemeral_pubkey,
            &encrypted_vault,
        );
        Ok(AgentCapsule {
            agent_id: agent_id.to_string(),
            source_node_pubkey: source_node_pubkey.to_string(),
            destination_node_pubkey: destination_node_pubkey.to_string(),
            migration_timestamp,
            migration_intent_nostr_event_id: None,
            encrypted_vault,
            vault_nonce,
            ephemeral_pubkey,
            capsule_hash,
            source_node_sig: String::new(),
        })
    }

    /// BLAKE3 commitment hash covering all plaintext identity + ciphertext fields.
    pub fn capsule_content_hash(
        agent_id: &str,
        source: &str,
        dest: &str,
        ts: u64,
        eph_pub_hex: &str,
        vault_ciphertext: &[u8],
    ) -> [u8; 32] {
        let mut hasher = blake3::Hasher::new();
        hasher.update(agent_id.as_bytes());
        hasher.update(b"|");
        hasher.update(source.as_bytes());
        hasher.update(b"|");
        hasher.update(dest.as_bytes());
        hasher.update(b"|");
        hasher.update(&ts.to_be_bytes());
        hasher.update(b"|");
        hasher.update(eph_pub_hex.as_bytes());
        hasher.update(b"|");
        hasher.update(vault_ciphertext);
        *hasher.finalize().as_bytes()
    }
}

/// Convert an Ed25519 `VerifyingKey` to its X25519 Montgomery-form public key.
/// Uses the birational equivalence u = (1 + y) / (1 - y) mod p via
/// `curve25519_dalek::EdwardsPoint::to_montgomery()`.
fn ed25519_vk_to_x25519_pk(vk: &VerifyingKey) -> X25519Public {
    use curve25519_dalek::edwards::CompressedEdwardsY;
    let compressed = CompressedEdwardsY(vk.to_bytes());
    let edwards = compressed
        .decompress()
        .expect("valid VerifyingKey must decompress");
    let montgomery = edwards.to_montgomery();
    X25519Public::from(*montgomery.as_bytes())
}

/// Convert an Ed25519 `SigningKey` to an X25519 `StaticSecret`.
/// The X25519 private scalar is SHA-512(seed)[0..32] with RFC 7748 clamping,
/// which is exactly the same scalar Ed25519 uses internally.
fn ed25519_sk_to_x25519_sk(sk: &SigningKey) -> x25519_dalek::StaticSecret {
    use sha2::Digest;
    let mut h = sha2::Sha512::new();
    h.update(sk.to_bytes()); // to_bytes() returns the 32-byte seed
    let hash = h.finalize();
    let mut scalar = [0u8; 32];
    scalar.copy_from_slice(&hash[..32]);
    // RFC 7748 clamping
    scalar[0]  &= 248;
    scalar[31] &= 127;
    scalar[31] |= 64;
    x25519_dalek::StaticSecret::from(scalar)
}

fn current_unix_ts() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::SigningKey as EdSk;
    use rand::rngs::OsRng;

    #[test]
    fn capsule_hash_is_deterministic() {
        let h1 = AgentCapsule::capsule_content_hash(
            "agent-abc123", "src_pubkey", "dst_pubkey", 1_700_000_000, "eph", b"vault_bytes",
        );
        let h2 = AgentCapsule::capsule_content_hash(
            "agent-abc123", "src_pubkey", "dst_pubkey", 1_700_000_000, "eph", b"vault_bytes",
        );
        assert_eq!(h1, h2);
    }

    #[test]
    fn capsule_hash_changes_with_any_field() {
        let base = AgentCapsule::capsule_content_hash(
            "agent-abc", "src", "dst", 1_000, "eph", b"vault",
        );
        let diff_agent = AgentCapsule::capsule_content_hash(
            "agent-xyz", "src", "dst", 1_000, "eph", b"vault",
        );
        let diff_vault = AgentCapsule::capsule_content_hash(
            "agent-abc", "src", "dst", 1_000, "eph", b"different_vault",
        );
        assert_ne!(base, diff_agent);
        assert_ne!(base, diff_vault);
    }

    #[test]
    fn seal_compat_shim_produces_valid_capsule() {
        let capsule = AgentCapsule::seal(
            b"fake_vault_data", "agent-test", "src_pubkey_hex", "dst_pubkey_hex",
        )
        .expect("seal must succeed");
        assert_eq!(capsule.agent_id, "agent-test");
        assert_eq!(capsule.encrypted_vault, b"fake_vault_data");
        assert_eq!(capsule.capsule_hash.len(), 32);
        // Hash must match independent computation with the compat shim's fixed eph value.
        let expected = AgentCapsule::capsule_content_hash(
            "agent-test", "src_pubkey_hex", "dst_pubkey_hex",
            capsule.migration_timestamp, &capsule.ephemeral_pubkey, b"fake_vault_data",
        );
        assert_eq!(capsule.capsule_hash, expected);
    }

    #[test]
    fn seal_encrypted_roundtrip() {
        let src_sk = EdSk::generate(&mut OsRng);
        let dst_sk = EdSk::generate(&mut OsRng);
        let vault = b"sovereign agent vault data - private keys inside";

        let capsule = AgentCapsule::seal_encrypted(
            vault, "test-agent", &src_sk, &dst_sk.verifying_key(),
        )
        .expect("seal_encrypted must succeed");

        // Verify signature exists.
        assert!(!capsule.source_node_sig.is_empty());
        // Verify ciphertext is different from plaintext.
        assert_ne!(capsule.encrypted_vault, vault);

        // Decrypt and verify round-trip.
        let decrypted = capsule.open(&dst_sk).expect("open must succeed");
        assert_eq!(decrypted, vault);
    }

    #[test]
    fn seal_encrypted_wrong_key_fails() {
        let src_sk = EdSk::generate(&mut OsRng);
        let dst_sk = EdSk::generate(&mut OsRng);
        let wrong_sk = EdSk::generate(&mut OsRng);

        let capsule = AgentCapsule::seal_encrypted(
            b"secret", "agent", &src_sk, &dst_sk.verifying_key(),
        )
        .expect("seal ok");

        let result = capsule.open(&wrong_sk);
        assert!(result.is_err(), "wrong key must fail to decrypt");
    }

    #[test]
    fn migration_state_serialises() {
        let state = MigrationState::IntentPublished {
            nostr_event_id: "event123".to_string(),
        };
        let json = serde_json::to_string(&state).expect("must serialise");
        assert!(json.contains("IntentPublished"));
    }
}
