/// Operator configuration schema for omokoda.toml.
///
/// This is an additive layer alongside the existing settings.json / AgentConfig system.
/// It lives at `~/.omokoda/config.toml` and is generated by `omokoda onboard`.
///
/// It configures the **runtime habitat** — which subsystems are enabled, what
/// external services to contact, and what the agent's identity looks like to the
/// outside world.  It does **not** authorise actions; see `constitution/` for policy.
use serde::{Deserialize, Serialize};
use std::path::Path;

// ---------------------------------------------------------------------------
// Section structs
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct AgentSection {
    pub name: String,
    pub display_name: String,
    /// Deployment environment tag, e.g. "local", "staging", "production"
    pub environment: String,
    /// Operating mode: "sovereign" | "hive-member" | "observer"
    pub mode: String,
}

impl Default for AgentSection {
    fn default() -> Self {
        Self {
            name: String::new(),
            display_name: String::new(),
            environment: "local".to_string(),
            mode: "sovereign".to_string(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ModelSection {
    /// Provider name, e.g. "anthropic", "openai"
    pub provider: String,
    /// Model identifier, e.g. "claude-sonnet-4-6"
    pub model: String,
    pub temperature: f32,
    pub max_tokens: u32,
    pub reasoning_enabled: bool,
    pub fallback_enabled: bool,
}

impl Default for ModelSection {
    fn default() -> Self {
        Self {
            provider: String::new(),
            model: String::new(),
            temperature: 0.7,
            max_tokens: 8192,
            reasoning_enabled: true,
            fallback_enabled: true,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MemorySection {
    pub enabled: bool,
    pub episodic: bool,
    pub semantic: bool,
    pub procedural: bool,
    pub dream: bool,
    /// GlyphIndex integration
    pub gix: bool,
    /// Mycelium stigmergic substrate (requires external gateway)
    pub mycelium: bool,
}

impl Default for MemorySection {
    fn default() -> Self {
        Self {
            enabled: true,
            episodic: true,
            semantic: true,
            procedural: true,
            dream: true,
            gix: true,
            mycelium: false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct IfaScriptSection {
    pub enabled: bool,
    /// Gate check required before any tool action
    pub required_for_action: bool,
    /// Gate check required before any state mutation
    pub required_for_mutation: bool,
    /// Odù symbol space (256 = one per Odù)
    pub odu_space: u32,
    /// Composed divination space (256×256)
    pub composed_space: u32,
}

impl Default for IfaScriptSection {
    fn default() -> Self {
        Self {
            enabled: true,
            required_for_action: true,
            required_for_mutation: true,
            odu_space: 256,
            composed_space: 65536,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct HermeticSection {
    pub enabled: bool,
    /// Number of Hermetic principles to enforce (max 7)
    pub principles: u8,
    pub hive_scope: bool,
    pub human_scope: bool,
    pub environment_scope: bool,
}

impl Default for HermeticSection {
    fn default() -> Self {
        Self {
            enabled: true,
            principles: 7,
            hive_scope: true,
            human_scope: true,
            environment_scope: true,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SecuritySection {
    /// Sandbox tool execution
    pub sandbox: bool,
    /// Enforce workspace filesystem boundary
    pub workspace_boundary: bool,
    /// Block SSRF / outbound request injection
    pub ssrf_guard: bool,
    /// All acts must produce an ARP receipt
    pub receipt_required: bool,
}

impl Default for SecuritySection {
    fn default() -> Self {
        Self {
            sandbox: true,
            workspace_boundary: true,
            ssrf_guard: true,
            receipt_required: true,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ToolsSection {
    pub enabled: bool,
}

impl Default for ToolsSection {
    fn default() -> Self {
        Self { enabled: true }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SkillsSection {
    pub enabled: bool,
    pub auto_discovery: bool,
}

impl Default for SkillsSection {
    fn default() -> Self {
        Self {
            enabled: true,
            auto_discovery: true,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct HeartbeatSection {
    pub enabled: bool,
    /// ISO 8601 duration string, e.g. "5m", "30s"
    pub interval: String,
}

impl Default for HeartbeatSection {
    fn default() -> Self {
        Self {
            enabled: true,
            interval: "5m".to_string(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct HiveSection {
    pub enabled: bool,
    /// "sovereign" | "lobe" | "coordinator"
    pub role: String,
}

impl Default for HiveSection {
    fn default() -> Self {
        Self {
            enabled: false,
            role: "sovereign".to_string(),
        }
    }
}

/// Generic external service block used for Vantage, Zàngbétò, OSOVM, UCX, Waggle.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ServiceSection {
    pub enabled: bool,
    pub url: String,
}

impl Default for ServiceSection {
    fn default() -> Self {
        Self {
            enabled: false,
            url: String::new(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TelemetrySection {
    pub enabled: bool,
}

impl Default for TelemetrySection {
    fn default() -> Self {
        Self { enabled: false }
    }
}

// ---------------------------------------------------------------------------
// Root config
// ---------------------------------------------------------------------------

/// Top-level operator configuration.  All sections are optional; missing
/// sections fall back to their `Default` implementations so the agent starts
/// successfully with an empty or partially-filled config.toml.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct OmokodaConfig {
    pub agent: AgentSection,
    pub model: ModelSection,
    pub memory: MemorySection,
    #[serde(rename = "ifascript")]
    pub ifascript: IfaScriptSection,
    pub hermetic: HermeticSection,
    pub security: SecuritySection,
    pub tools: ToolsSection,
    pub skills: SkillsSection,
    pub heartbeat: HeartbeatSection,
    pub hive: HiveSection,
    pub vantage: ServiceSection,
    pub zangbeto: ServiceSection,
    pub osovm: ServiceSection,
    pub ucx: ServiceSection,
    pub waggle: ServiceSection,
    pub telemetry: TelemetrySection,
}

impl Default for OmokodaConfig {
    fn default() -> Self {
        Self {
            agent: AgentSection::default(),
            model: ModelSection::default(),
            memory: MemorySection::default(),
            ifascript: IfaScriptSection::default(),
            hermetic: HermeticSection::default(),
            security: SecuritySection::default(),
            tools: ToolsSection::default(),
            skills: SkillsSection::default(),
            heartbeat: HeartbeatSection::default(),
            hive: HiveSection::default(),
            vantage: ServiceSection::default(),
            zangbeto: ServiceSection::default(),
            osovm: ServiceSection::default(),
            ucx: ServiceSection::default(),
            waggle: ServiceSection::default(),
            telemetry: TelemetrySection::default(),
        }
    }
}

// ---------------------------------------------------------------------------
// I/O helpers
// ---------------------------------------------------------------------------

impl OmokodaConfig {
    /// Load config from `path`.  Returns an error if the file exists but
    /// cannot be parsed.  Use [`load_or_default`] to silently fall back.
    pub fn load(path: &Path) -> Result<Self, Box<dyn std::error::Error>> {
        let content = std::fs::read_to_string(path)?;
        let cfg: Self = toml::from_str(&content)?;
        Ok(cfg)
    }

    /// Load config from `path`, returning `Default::default()` if the file is
    /// absent.  Parse errors are logged to stderr but do not panic.
    pub fn load_or_default(path: &Path) -> Self {
        if !path.exists() {
            return Self::default();
        }
        match Self::load(path) {
            Ok(cfg) => cfg,
            Err(e) => {
                eprintln!(
                    "[omokoda] Warning: failed to parse config at {}: {}. Using defaults.",
                    path.display(),
                    e
                );
                Self::default()
            }
        }
    }

    /// Write a well-commented default config.toml to `path`.
    /// Parent directories must already exist.
    pub fn write_default(path: &Path) -> std::io::Result<()> {
        let content = Self::default_toml_string();
        std::fs::write(path, content)
    }

    /// Returns the commented default config as a `String`.
    pub fn default_toml_string() -> String {
        r#"# ~/.omokoda/config.toml — operator configuration
# Generated by: omokoda onboard
# This file configures the runtime habitat.
# It does NOT authorize actions — see constitution/ for policy.
#
# All sections are optional. Omitted keys fall back to the built-in defaults.

# ---------------------------------------------------------------------------
# Agent identity
# ---------------------------------------------------------------------------
[agent]
# Canonical machine name (no spaces).  Required by Vantage/Nostr registration.
name = ""
# Human-readable label shown in logs and the Vantage dashboard.
display_name = ""
# Deployment context: "local" | "staging" | "production"
environment = "local"
# Operating mode: "sovereign" | "hive-member" | "observer"
mode = "sovereign"

# ---------------------------------------------------------------------------
# Language model
# ---------------------------------------------------------------------------
[model]
# Provider: "anthropic" | "openai" | ""  (empty = use default from settings.json)
provider = ""
# Model identifier: "claude-sonnet-4-6", "gpt-4o", ...
model = ""
temperature = 0.7
max_tokens = 8192
reasoning_enabled = true
fallback_enabled = true

# ---------------------------------------------------------------------------
# Memory subsystems
# ---------------------------------------------------------------------------
[memory]
enabled = true
episodic = true
semantic = true
procedural = true
dream = true
# GlyphIndex (content-hash glyph graph, no plaintext retained)
gix = true
# Mycelium stigmergic substrate — requires external Go gateway on port 7795
mycelium = false

# ---------------------------------------------------------------------------
# Ifá Script gate checks
# ---------------------------------------------------------------------------
[ifascript]
enabled = true
# Block tool invocation unless gate score passes
required_for_action = true
# Block state mutations unless gate score passes
required_for_mutation = true
# 256 = one entry per Odù
odu_space = 256
# 256 × 256 composed divination space
composed_space = 65536

# ---------------------------------------------------------------------------
# Hermetic law enforcement
# ---------------------------------------------------------------------------
[hermetic]
enabled = true
# 1–7: how many of the 7 Hermetic principles to enforce
principles = 7
hive_scope = true
human_scope = true
environment_scope = true

# ---------------------------------------------------------------------------
# Security hardening
# ---------------------------------------------------------------------------
[security]
sandbox = true
workspace_boundary = true
ssrf_guard = true
# Every act must produce a signed ARP receipt
receipt_required = true

# ---------------------------------------------------------------------------
# Tool and skill loading
# ---------------------------------------------------------------------------
[tools]
enabled = true

[skills]
enabled = true
auto_discovery = true

# ---------------------------------------------------------------------------
# Heartbeat
# ---------------------------------------------------------------------------
[heartbeat]
enabled = true
# ISO-8601-style duration string: "5m", "30s", "1h"
interval = "5m"

# ---------------------------------------------------------------------------
# Hive mind participation (Omokoda macro hive)
# ---------------------------------------------------------------------------
[hive]
enabled = false
# "sovereign" | "lobe" | "coordinator"
role = "sovereign"

# ---------------------------------------------------------------------------
# External service connections
# All disabled by default; set enabled = true and provide the URL.
# ---------------------------------------------------------------------------

[vantage]
enabled = false
url = ""

[zangbeto]
enabled = false
url = ""

[osovm]
enabled = false
url = ""

[ucx]
enabled = false
url = ""

[waggle]
enabled = false
url = ""

# ---------------------------------------------------------------------------
# Telemetry
# ---------------------------------------------------------------------------
[telemetry]
enabled = false
"#
        .to_string()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_roundtrip() {
        let cfg = OmokodaConfig::default();
        let serialised = toml::to_string_pretty(&cfg).expect("serialise");
        let parsed: OmokodaConfig = toml::from_str(&serialised).expect("deserialise");
        assert_eq!(cfg, parsed);
    }

    #[test]
    fn empty_file_gives_defaults() {
        let cfg: OmokodaConfig = toml::from_str("").expect("empty TOML should parse fine");
        assert_eq!(cfg, OmokodaConfig::default());
    }

    #[test]
    fn partial_override() {
        let src = r#"
[agent]
name = "hermes"
environment = "production"

[model]
provider = "anthropic"
temperature = 0.3
"#;
        let cfg: OmokodaConfig = toml::from_str(src).expect("parse");
        assert_eq!(cfg.agent.name, "hermes");
        assert_eq!(cfg.agent.environment, "production");
        assert_eq!(cfg.agent.mode, "sovereign");
        assert_eq!(cfg.model.provider, "anthropic");
        assert!((cfg.model.temperature - 0.3_f32).abs() < 1e-6);
        assert_eq!(cfg.model.max_tokens, 8192);
        assert!(cfg.model.reasoning_enabled);
        assert!(cfg.memory.enabled);
        assert!(!cfg.hive.enabled);
    }

    #[test]
    fn default_toml_string_parses() {
        let src = OmokodaConfig::default_toml_string();
        let cfg: OmokodaConfig = toml::from_str(&src).expect("default string must parse");
        assert_eq!(cfg, OmokodaConfig::default());
    }

    #[test]
    fn write_and_load() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("config.toml");
        OmokodaConfig::write_default(&path).expect("write");
        let loaded = OmokodaConfig::load(&path).expect("load");
        assert_eq!(loaded, OmokodaConfig::default());
    }
}
