//! Move codegen — compiles an OsoIR contract schema to a Move module.
//!
//! Pipeline:
//!   OsoIR (contract schema) → MoveCodegen::compile() → Move source string
//!
//! The generated module follows the Sui Move dialect:
//!   - One `struct` per AssetSpec with `key, store` abilities
//!   - One `public entry fun` per lifecycle transition
//!   - Capability checks at function entry
//!   - Evidence assertion before settlement calls
//!   - `sui::transfer::public_transfer` stub for TRANSFER opcode
//!   - Sui event emission stub for EMIT_RECEIPT opcode
//!   - Cross-module call stub for AGENT_CALL opcode
//!
//! For VM-level IrProgram inputs, each instruction that maps to a
//! Call/Transfer/Emit opcode gets its own entry function; all other
//! opcodes become inline comments.

use crate::ir::{AssetSpec, OsoIR};
use std::fmt::Write as FmtWrite;

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub enum CompileError {
    /// contract_name did not satisfy the PascalCase rule.
    InvalidContractName(String),
    /// assets list was empty.
    EmptyAssets,
    /// lifecycle list was empty.
    EmptyLifecycle,
    /// oso_ir_version is not "1.0".
    UnknownVersion(String),
    /// A work contract did not declare any capabilities.
    MissingCapability,
    /// Internal formatting error (should not happen).
    FormatError(String),
}

impl std::fmt::Display for CompileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidContractName(n) => write!(f, "contract_name fails PascalCase rule: {}", n),
            Self::EmptyAssets => write!(f, "assets cannot be empty"),
            Self::EmptyLifecycle => write!(f, "lifecycle cannot be empty"),
            Self::UnknownVersion(v) => write!(f, "unknown oso_ir_version: {}", v),
            Self::MissingCapability => {
                write!(f, "work contracts must declare at least one capability")
            }
            Self::FormatError(e) => write!(f, "format error: {}", e),
        }
    }
}

// ---------------------------------------------------------------------------
// MoveCodegen
// ---------------------------------------------------------------------------

pub struct MoveCodegen;

impl MoveCodegen {
    /// Compile an OsoIR contract schema to a Move module source string.
    pub fn compile(ir: &OsoIR) -> Result<String, CompileError> {
        // --- validation ---
        if ir.oso_ir_version != "1.0" {
            return Err(CompileError::UnknownVersion(ir.oso_ir_version.clone()));
        }
        if !is_pascal_case(&ir.contract_name) {
            return Err(CompileError::InvalidContractName(ir.contract_name.clone()));
        }
        if ir.assets.is_empty() {
            return Err(CompileError::EmptyAssets);
        }
        if ir.lifecycle.is_empty() {
            return Err(CompileError::EmptyLifecycle);
        }
        if ir.contract_class == "work" && ir.capabilities.is_empty() {
            return Err(CompileError::MissingCapability);
        }

        let module_name = sanitize_module_name(&ir.contract_name);
        let mut out = String::new();

        // --- module header ---
        emit_header(&mut out, ir, &module_name)?;

        // --- imports ---
        emit_imports(&mut out)?;

        // --- asset structs ---
        for asset in &ir.assets {
            emit_struct(&mut out, asset)?;
        }

        // --- lifecycle state enum (as constants) ---
        emit_lifecycle_constants(&mut out, &ir.lifecycle)?;

        // --- lifecycle transition entry functions ---
        emit_lifecycle_fns(&mut out, ir)?;

        // --- settlement function ---
        emit_settlement_fn(&mut out, ir)?;

        // --- module close ---
        writeln!(out, "}}").map_err(|e| CompileError::FormatError(e.to_string()))?;

        Ok(out)
    }
}

// ---------------------------------------------------------------------------
// Emitters
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, ir: &OsoIR, module_name: &str) -> Result<(), CompileError> {
    writeln!(out, "// Generated by oso-move v0.1.0 — DO NOT EDIT")
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "// Contract: {} ({})",
        ir.contract_name, ir.contract_class
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out, "// OSO-IR version: {}", ir.oso_ir_version)
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "// Minimum tier: {}  Currency: {}",
        ir.minimum_tier, ir.settlement.currency
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out, "module oso_contracts::{} {{", module_name)
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    Ok(())
}

fn emit_imports(out: &mut String) -> Result<(), CompileError> {
    let imports = [
        "    use sui::tx_context::TxContext;",
        "    use sui::tx_context;",
        "    use sui::transfer;",
        "    use sui::event;",
        "    use sui::object::{Self, UID};",
    ];
    writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;
    for import in &imports {
        writeln!(out, "{}", import).map_err(|e| CompileError::FormatError(e.to_string()))?;
    }
    writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;
    Ok(())
}

fn emit_struct(out: &mut String, asset: &AssetSpec) -> Result<(), CompileError> {
    writeln!(
        out,
        "    /// Auto-generated from AssetSpec \"{}\"",
        asset.name
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out, "    struct {} has key, store {{", asset.name)
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out, "        id: UID,").map_err(|e| CompileError::FormatError(e.to_string()))?;
    for field in &asset.fields {
        // All fields are u64 by default; type resolution is a Phase 23.2 task.
        writeln!(out, "        {}: u64, // TODO: resolve field type", field)
            .map_err(|e| CompileError::FormatError(e.to_string()))?;
    }
    writeln!(out, "    }}").map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;
    Ok(())
}

fn emit_lifecycle_constants(out: &mut String, lifecycle: &[String]) -> Result<(), CompileError> {
    writeln!(out, "    // --- Lifecycle state constants ---")
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    for (i, state) in lifecycle.iter().enumerate() {
        writeln!(out, "    const STATE_{}: u8 = {};", state, i)
            .map_err(|e| CompileError::FormatError(e.to_string()))?;
    }
    writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;
    Ok(())
}

fn emit_lifecycle_fns(out: &mut String, ir: &OsoIR) -> Result<(), CompileError> {
    // Generate one transition function per consecutive state pair.
    // e.g. CREATED → ASSIGNED becomes `transition_created_to_assigned`.
    let states = &ir.lifecycle;

    for window in states.windows(2) {
        let from = window[0].to_lowercase();
        let to = window[1].to_lowercase();
        let fn_name = format!("transition_{}_to_{}", from, to);

        writeln!(
            out,
            "    /// Lifecycle transition: {} → {}",
            window[0], window[1]
        )
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
        writeln!(
            out,
            "    public entry fun {}(ctx: &mut TxContext) {{",
            fn_name
        )
        .map_err(|e| CompileError::FormatError(e.to_string()))?;

        // Capability checks
        if !ir.capabilities.is_empty() {
            writeln!(out, "        // TODO: assert capability grants")
                .map_err(|e| CompileError::FormatError(e.to_string()))?;
            for cap in &ir.capabilities {
                writeln!(
                    out,
                    "        // assert!(has_capability(tx_context::sender(ctx), b\"{}\"), ECAPABILITY_MISSING);",
                    cap
                )
                .map_err(|e| CompileError::FormatError(e.to_string()))?;
            }
        }

        // Evidence assertion on settlement-adjacent transitions
        if (window[1] == "SETTLED" || window[1] == "VERIFIED") && ir.evidence.required {
            writeln!(
                out,
                "        // assert_evidence: type={}",
                ir.evidence.kind.as_deref().unwrap_or("any")
            )
            .map_err(|e| CompileError::FormatError(e.to_string()))?;
            writeln!(
                out,
                "        // TODO: EvidenceCommitment check before settlement"
            )
            .map_err(|e| CompileError::FormatError(e.to_string()))?;
        }

        writeln!(
            out,
            "        // state transition: {} → {}",
            window[0], window[1]
        )
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
        writeln!(out, "        let _sender = tx_context::sender(ctx);")
            .map_err(|e| CompileError::FormatError(e.to_string()))?;
        writeln!(
            out,
            "        // TODO: update state field to STATE_{}",
            window[1]
        )
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
        writeln!(out, "    }}").map_err(|e| CompileError::FormatError(e.to_string()))?;
        writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;
    }

    Ok(())
}

fn emit_settlement_fn(out: &mut String, ir: &OsoIR) -> Result<(), CompileError> {
    writeln!(
        out,
        "    /// Settlement: distribute Àṣẹ per fee routing policy."
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "    /// currency={} fee_routing={} provider_share={}",
        ir.settlement.currency, ir.settlement.fee_routing, ir.settlement.provider_share
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "    public entry fun settle(provider: address, amount: u64, ctx: &mut TxContext) {{"
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "        // TRANSFER opcode → sui::transfer::public_transfer stub"
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "        // TODO: sui::transfer::public_transfer(coin, provider);"
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;

    // Emit receipt event
    writeln!(out, "        // EMIT_RECEIPT opcode → event emission stub")
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "        // TODO: event::emit(SettlementReceipt {{ provider, amount }});"
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;

    // Esu tithe comment if policy declares it
    if let Some(tithe) = ir.policy.get("esu_tithe") {
        writeln!(
            out,
            "        // Èṣù tithe: {} of settlement flows to justice pool",
            tithe
        )
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
        writeln!(
            out,
            "        // TODO: transfer tithe to ESU_JUSTICE_POOL address"
        )
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    }

    writeln!(out, "        let _ctx = ctx;")
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "        let (_provider, _amount) = (provider, amount);"
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out, "    }}").map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;

    // AGENT_CALL stub
    writeln!(out, "    /// AGENT_CALL opcode — cross-module call stub.")
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "    public entry fun agent_call(target: address, _ctx: &mut TxContext) {{"
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(
        out,
        "        // TODO: call target module via dynamic dispatch (Sui PTB)"
    )
    .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out, "        let _target = target;")
        .map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out, "    }}").map_err(|e| CompileError::FormatError(e.to_string()))?;
    writeln!(out).map_err(|e| CompileError::FormatError(e.to_string()))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Sanitize a PascalCase contract name into a snake_case Move module identifier.
/// e.g. "AsePool" → "ase_pool", "AgentRegistry" → "agent_registry"
pub fn sanitize_module_name(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// Check that a string satisfies PascalCase: starts with uppercase, alphanumeric only.
fn is_pascal_case(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) if first.is_ascii_uppercase() => chars.all(|c| c.is_ascii_alphanumeric()),
        _ => false,
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_ase_pool() {
        assert_eq!(sanitize_module_name("AsePool"), "ase_pool");
    }

    #[test]
    fn sanitize_agent_registry() {
        assert_eq!(sanitize_module_name("AgentRegistry"), "agent_registry");
    }

    #[test]
    fn is_pascal_valid() {
        assert!(is_pascal_case("AsePool"));
        assert!(is_pascal_case("AgentRegistry"));
        assert!(is_pascal_case("GPUComputeMarketplace"));
    }

    #[test]
    fn is_pascal_invalid() {
        assert!(!is_pascal_case("asePool"));
        assert!(!is_pascal_case(""));
        assert!(!is_pascal_case("_bad"));
    }
}
